[workspace]
members = ["crates/*"]
resolver = "2"
[workspace.package]
version = "0.0.15"
edition = "2021"
authors = ["bmbp<rs_bmbp.163.com>"]
description = "BMBP Marco"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/bmbper/bmbp_marco"
repository = "https://github.com/bmbper/bmbp_marco"
documentation = "https://github.com/bmbper/bmbp_marco"
[workspace.dependencies]
bmbp_marco_util = { version = "0.0.15", path = "crates/bmbp_marco_util" }
bmbp_marco_bean = { version = "0.0.15", path = "crates/bmbp_marco_bean" }
bmbp_marco_rdbc = { version = "0.0.16", path = "crates/bmbp_marco_rdbc" }
bmbp_marco_curd = { version = "0.0.15", path = "crates/bmbp_marco_curd" }
bmbp_rdbc_type = "0.3.0"
bmbp_util = "0.0.6"
case_style = "0.2.1"
serde = { version = "1.0.204", features = ["derive"] }
syn =  "2.0.72"
quote = "1.0.36"
proc-macro2 = "1.0.86"
